# Generated by Django 4.2.16 on 2024-09-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('img', models.URLField()),
                ('external_link', models.URLField()),
            ],
        ),
    ]
