# Generated by Django 4.2.14 on 2024-07-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='otp',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
