# Generated by Django 4.2.14 on 2024-07-22 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f3fc830d-c19b-4343-a6da-59874bb89d58'), editable=False, primary_key=True, serialize=False),
        ),
    ]
