# Generated by Django 4.2.14 on 2024-08-06 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
