# Generated by Django 4.2.14 on 2024-08-06 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogmodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
