# Generated by Django 4.2.15 on 2024-08-12 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/products')),
                ('category', models.CharField(choices=[('Electonics', 'Electronics'), ('Mobiles', 'Mobiles'), ('Computer', 'Computer'), ('Clothes', 'Clothes'), ('Toys', 'Toys'), ('Grocery', 'Grocery')], max_length=50)),
                ('description', models.TextField()),
                ('sku', models.CharField(max_length=50)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
        ),
    ]
