# Generated by Django 4.2.14 on 2024-07-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_brand_skills_products_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skills'},
        ),
    ]
