# Generated by Django 4.2.14 on 2024-07-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_studentdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
