# Generated by Django 4.2.14 on 2024-07-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_book_book_book_name_remove_book_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={},
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
