# Generated by Django 4.2.15 on 2024-08-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
