# Generated by Django 4.2.14 on 2024-07-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_img', models.ImageField(upload_to='image')),
                ('thumb_small', models.ImageField(blank=True, null=True, upload_to='image/thumbnails')),
                ('thumb_medium', models.ImageField(blank=True, null=True, upload_to='image/thumbnails')),
                ('thumb_large', models.ImageField(blank=True, null=True, upload_to='image/thumbnails')),
            ],
        ),
    ]
